[versions]
kotlin = "1.9.22"
kotlin_version = "2.0.20"

[libraries]
compose-compiler-gradle = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin_version" }

immutables = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version = "0.3.7" }

coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.1"
coroutines-android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.1"

[plugins]
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[bundles]
coroutines = ["coroutines-core", "coroutines-android"]
